import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Push Events
self.addEventListener('push', (event) => {
    let data = { title: 'Taskify Update', body: 'You have a new update!' };
    try {
        if (event.data) {
            data = event.data.json();
        }
    } catch (err) {
        if (event.data) {
            data = { title: 'Taskify Update', body: event.data.text() };
        }
    }

    const options = {
        body: data.body,
        icon: '/Task.png',
        badge: '/favicon.svg',
        data: {
            url: data.url || '/'
        }
    };

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            const targetUrl = event.notification.data.url || '/';
            
            // If window is already open, focus it
            for (const client of clientList) {
                const clientUrl = new URL(client.url).pathname;
                if (clientUrl === targetUrl && 'focus' in client) {
                    return client.focus();
                }
            }
            
            // Otherwise open a new window
            if (clients.openWindow) {
                return clients.openWindow(targetUrl);
            }
        })
    );
});
